### ISSUE TITLE
Refactor Triggers to own classes

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#101]
Refactor Triggers to own classes. Like Things, the triggers are probably stored as structs in C. Since we didn't have the structs really. We just ended up putting all in the same class. Not even subclassing it much. This makes them hard to use. Not all the fields mean the same for all  trigger types.

We should figure out the different structs and make them as classes. Maybe a sub package under KWD. And store them there. Not necessarily straight up using JAVA style C-structs like in the Things.

See also #19.

**Comment by ArchDemons** [comment]
I think we can close this issue and #19. My Trigger class not elegant but it better way to save so different attributes (like user data in Spatial). It can be a little bit improved (in part of user data), but not essentially.

If work with Trigger class will be uncomfortably, we can refactor it again. But in current state it`s look good (for me).
