### ISSUE TITLE
Implement 1st person camera

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#109]
Implement 1st person camera.

Requirements:
 - Switching in/out from regular view
 - Most likely the best option is to copy + paste the current game camera and start from there
 - Move about

Bonus features (easier to test etc. nice to have already etc.):
 - Cast posession to get there :)
 - Apply the first person masks & movement (creature record)
 - Move the actual entity (this point, hmm, the AI control needs to be disabled for this or something, might be too big for this scope)

**Comment by ArchDemons** [comment]
I have some question. It should be a screen controller like PlayerState or new state of stateManager current PlayerState?

**Comment by tonihele** [comment]
PlayerState is the puppet master, manages the player's states & GUI. So I would say that PlayerInteractionState should signal the PlayerState that posession takes place (I used anonymous class & override for the onInteractionStateChange, I'm not sure if it should be the same method or not, probably not..?). PlayerState should then proceed to disable the PlayerInteractionState and start the PlayerPosessionState and change the GUI. PlayerPosessionState would then in turn have its own camera. First person camera. This is how our design works currently.

So essentially. I would recommend copy + paste the start:
PlayerCamera + PlayerCameraState -> PlayerFirstPersonCamera + *State.
For example.

**Comment by ArchDemons** [comment]
Houston, we have a problem. Camera have nearPlane = 1f and floor culling when camera height < 1f.
If I change camera settings, I need to restore the previous camera state when exit of possession. But I dont know what how restore camera settrings.

**Comment by tonihele** [comment]
This is mission control, hearing you loud and clear :) PlayerCameraState is "master" for the PlayerCamera. The state just needs to implement the setEnabled. When it is set disabled it should save the camera settings, and restore the settings on enablation. I think this is a valid solution, if no one can't think of a better one. Of course then we need to remember to enable/disable the states in order.
