### ISSUE TITLE
Implement Posession GUI

### ISSUE THREAD

**Issue by ufdada** [tonihele/OpenKeeper#110]
As the title says implement the posession gui wise.

This means:
* Placeholder for healthbar
* Basic attacks
* Special attacks
* Grouping
* Map overview

Should help #109.

**Comment by ArchDemons** [comment]
I made a template. If we want to control the camera, I need a skeleton (where it on and off) of PossesionalState.

**Comment by ufdada** [comment]
If we don't find something in the kmf, i would prefer to use a dummy for now. Maybe we calculate one or just make these per hand, since it's not that many models.

For this task even the template should be enough.
