### ISSUE TITLE
Implement command console

### ISSUE THREAD

**Issue by ufdada** [tonihele/OpenKeeper#112]
This should make it easier to debug / cheat or anything like that.

Nifty has already a nice control for it:
https://github.com/void256/nifty-gui/wiki/Console

**Comment by ArchDemons** [comment]
I realize console. But what we want from it. I think cheats need move to console. But this solution not like original game. What you think Tony?

**Comment by tonihele** [comment]
I would instead make console appear from some key, BUT only if command line flag -debug is given. The cheats I would leave as is, classic mode :) We can also do the disabling of the console later, as now it makes sense to run without the debug flag but still have the console available on request.

For console, I don't have any specific needs right now, but something like these would make sense on some stage of debugging:

- giving gold, also negative amount, to test the room populating
- giving & taking mana, to test spells
- giving room type, spell as available
- change a slab type?
- spawn a creature to some map point, or without map point a random owned portal

Maybe all these to current player if not specified. Some easy to learn syntax

**Comment by tonihele** [comment]
This console stuff would be a DebugState we can neatly treat as separate code & appstate?

**Comment by belgianguy** [comment]
I read in one of the patch release notes that at one  point they removed the cheats from multiplayer :)

**Comment by ufdada** [comment]
Some debug information would be nice, like `creaturestatistics true` shows how many creatures every player has, how many of them are angry, have a bed, do train etc.

**Comment by tonihele** [comment]
Simply using toString() in PlayerCreatureControl etc. would be suffice?

**Comment by ufdada** [comment]
Basic implementation by ArchDemons  in #230

**Comment by ufdada** [comment]
Since #281 it has some functionality, so we can close this here. We just add stuff as we go.
