### ISSUE TITLE
Figure out & construct pillars to the rooms

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#116]
Figure out & construct pillars to the rooms. First, figure out the logic they are placed to the room. Aaaand contruct them.

**Comment by codenamecpp** [comment]
Seems treasury pillars are placed on specific tiles according to this scheme:
1) two neighbour tiles (for example, N and W) should not belong to this room instance,
2) neighbour tile SE should be inner (inner tile is center of 3x3 square within room)

See image: http://i.imgsafe.org/ff80734.png
Red circle is pillar, yellow tiles is treasury room and red tile is inner tile within room (room may have many of those)

**Comment by tonihele** [comment]
Thanks. And it seems that it is only available to rooms with construction type "Normal". But Lair & Training room doesn't build pillars (the objects/models are there, at least for lair). I don't know under what flag is it, so I'll just hard code it for now.

**Comment by ArchDemons** [comment]
I know, I know. https://cloud.mail.ru/public/jVDC/EAwQ7R6K6

1) The pillars are located only in the corners of the room
2) Inner tiles (size - the minimum size of the room, for example, 3x3) including tile pillar should be a room tile

**Comment by tonihele** [comment]
A bit hard coded bits, could find the pillar references and they are not got though the objects in any way.
