### ISSUE TITLE
Tile pulsate (Flash tile)

### ISSUE THREAD

**Issue by ArchDemons** [tonihele/OpenKeeper#137]
There must be an easy way to make tile pulsing red color once per second. Any ideas?

![shot0056](https://cloud.githubusercontent.com/assets/12515916/12518548/5a3055e6-c14a-11e5-8ebf-a50c1d6f36e3.jpg)

**Comment by tonihele** [comment]
Perhaps the most JME type solution is a control for each tile that also stores health etc. It can have the state and controls to achieve effects per tile. But having so much Controls in the hierarchy... I don't know, is it a performance killer? One could be TileAppState that just uses the entity records and does the visual stuff. This way multiple effects would run in sync. I could ask this in the JME forums.

**Comment by tonihele** [comment]
http://hub.jmonkeyengine.org/t/2d-tile-worlds-how-to-handle-the-tile-data/34915

**Comment by tonihele** [comment]
Hmm, maybe WorldHandler should actually be an AppState... A fast conclusion.

**Comment by ArchDemons** [comment]
Yep. List with pulsate tiles and current time - that is all what we need

**Comment by ufdada** [comment]
Isn't this already done?

**Comment by ArchDemons** [comment]
Not correct yet. I`ll fix it soon.

**Comment by ArchDemons** [comment]
PR rebased !!!
