### ISSUE TITLE
Create skin for the Nifty GUI

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#14]
Create skin for the Nifty GUI. We need skins for the basic components. The images are already extracted and everything. There is just skinning.

If possible the AssetConverter should create this. If not possible, manual creation is of course an option since it is needed after the asset conversion and the devs have the assets needed available.

**Comment by ArchDemons** [comment]
I take it

**Comment by tonihele** [comment]
Grrrrreat! You might have noticed the ones I made for example. In CheckBoxStyle.xml, MyControls.xml etc. Should maybe moved to a subfolder also. Soon (soonish, eventually..) we are upgrading to JME 3.1 which has Nifty 1.4. If I remember correctly it had only hierarchical changes on the CheckBox. So not much. This would at least affect the way I did those initial ones.

**Comment by meltzow** [comment]
Hi, 
just for discussion: its also possible to use tonegodgui. (see here http://wiki.jmonkeyengine.org/doku.php/jme3:contributions:tonegodgui )
A lot of guys (and I am one of them) have problems to understand and handle Nifty correct. Or is it better with 1.4? 
my two cents: tonegodgui are better integrated in JME and so you have full control over the code. What do you think?

**Comment by tonihele** [comment]
Nifty is still default in JME 3.1. And it is still being developed. I do admit it might not be the best (but not perhaps the worst either) and the discussion is valid.

I haven't yet seen any real obstacle with Nifty. All options should be considered, Lemur also seems to be in quite the hype now. One prominent option is JavaFX. The backing argument on JavaFX is that with JAVA 8 it is shipped by default and it should be the one and only GUI library for JAVA. The projection to JME is supposed to be a breeze?

I have only experience in Nifty. I'm not sure what the version 1.4 brings.

**Comment by meltzow** [comment]
I found a changelog for nifty 1.4. http://download2.polytechnic.edu.na/pub4/sourceforge/n/project/ni/nifty-gui/nifty-gui/1.4/nifty-1.4.0-changelog.txt

**Comment by ufdada** [comment]
As java7 is eol (end of life) afaik, java8 support shouldn't be that hard. javafx is actually pretty neat, i wrote some small apps with it.

**Comment by meltzow** [comment]
@ufdada do you have some code examples for javafx with JME?

**Comment by tonihele** [comment]
Yeah, I'm the only one I think holding us back from JAVA 8 :) The plan was to introduce it with JME 3.1, as the 3.0 JDK is currently difficult with JAVA 8. Yes yes, gradle & Eclipse, but I'm lazy.

I tried to create our conversion GUIs with JavaFX initially but gave up pretty fast :)

**Comment by ufdada** [comment]
@meltzow sorry but i used it only in enterprise desktop applications, not in jme yet.

Some links to check out:
http://hub.jmonkeyengine.org/t/javafx-embedded-in-jme3/27747
https://github.com/empirephoenix/JME3-JFX

**Comment by tonihele** [comment]
Time frame doing a possible switch I'd say is after JME 3.1 switch. Nifty shouldn't be too hard to migrate, and changing now top something else and migrating it to 3.1 is just a lot of work. Especially when I think there is nothing wrong with our current GUI. Lacks polish perhaps.

I suspect that migration to JME 3.1 is closer than any large GUI feature implementation currently.

**Comment by meltzow** [comment]
Yes man, we understand it. And we are understand your the lazy thing. I am out at this issue if Nifty is used.

**Comment by tonihele** [comment]
Going to close this, the scope is too big on this issue. And much is already done. Need to break this to smaller issues is needed.

If we still need some other GUI framework than Nifty, also another issue. We have now more clearer vision of what is available and what are the requirements for such framework. But as it stands we are now in JME 3.1 & Nifty 1.4.
