### ISSUE TITLE
Implement job queue

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#148]
Implement job queue. This is the big thing. Workers should work. Few jobs would be nice also for example. Jobs need location, access points, max number of workers etc.

Digging out a tile & claiming one would be requirements for example jobs.

**Comment by ufdada** [comment]
Nice work done so far :). You should probably also consider that these jobs have a priority (1. Digging 2. claiming tiles 3. fortifying walls)

**Comment by tonihele** [comment]
Thanks. I also saw that they have a priority. I think digging & claiming might have the same priority even. As the fortifying walls is very low priority. But there is also priority based on the distance of these tasks. At least it seems so. I think some sort of point calculating system is needed.

**Comment by ufdada** [comment]
Probably something similar to the path finding system (where water and lava has a higher cost etc.). Seems reasonable.

**Comment by tonihele** [comment]
I first thought that I'd go with manhattan distance on these. But ended up doing path finds on each task. It might get heavy at some point. Though our scale is quite small. So at least currently we have the exact distance even.

**Comment by ufdada** [comment]
I think this is actually a better approach. Any idea what the unknown values of [JobPreference](https://github.com/tonihele/OpenKeeper/blob/master/src/toniarts/openkeeper/tools/convert/map/Creature.java#L2398) are? Might come in handy for this task.

**Comment by tonihele** [comment]
Hmm, no idea still. But good that you reminded me of those. I need to tie the tasks to those also.

**Comment by tonihele** [comment]
Basic task prioritizing implemented, so the tasking seems less goofy as the imps tend to do tasks near them. I just made up some priorities, not scientifically selected ones. Except followed the editor a bit, I think 0-255 is used for prioritizing (looked at the object pick up priority), but how it is calculated is beyond me. Now I just add it to a manhattan distance and hope for the best :)

A basic gold economy is done. A very basic one.

**Comment by tonihele** [comment]
The thing is basically done. Of course not perfect. And no icons, but we don't have flowers yet either. But there is so much basic framework stuff included with this merge, like gold economy and what not. Shit ton of stuff!

**Comment by tonihele** [comment]
Normal creatures can make up a lair. An example job for the basic creatures.
