### ISSUE TITLE
Implement creature loader

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#15]
Implement creature loader. The loading and the logic is in the creature data file. We should respect the animation and mesh guides etc.

**Comment by meltzow** [comment]
first try in https://github.com/meltzow/OpenKeeper/tree/feature-15

**Comment by tonihele** [comment]
Looks ok to me (didn't test), except style wise the file values reading could be in KwdFile instead of the newly introduced class Tile. Just because it is so in the rest. Good or bad, but style breaking.

**Comment by meltzow** [comment]
created a pullrequest now. https://github.com/tonihele/OpenKeeper/pull/91 
perhaps this is closed now
