### ISSUE TITLE
Case sensitive assets

### ISSUE THREAD

**Issue by ufdada** [tonihele/OpenKeeper#153]
As DK was built for windows, which is not case sensitive, the designers didn't really cared about it (at least it seems like that). This leads to problems on loading the correct models.

We could fix this in at least two ways:
1. Generate the assets in one case (lower or upper)
2. Make the Assetloader case insensitive (as it already recognizes the wrong case it might be an easy thing to do)

**Comment by ArchDemons** [comment]
I vote for lower case assets names. But if the second option is easy to make, maybe start with it

**Comment by tonihele** [comment]
Yeah, my OCD led to not touching the names. I wanted to preserve any possible human readability in CamelCasing. But this was perhaps overreacting that costs us in the long run.

This was very much present in the model - texture mapping. So I kinda did 2) already, it is just not automatic. It is here:
https://github.com/tonihele/OpenKeeper/blob/master/src/toniarts/openkeeper/tools/convert/ConversionUtils.java#L421

**Comment by ArchDemons** [comment]
In addition to searching asset on the disc (take time), we also look for his correct name (take more time). Good thing though we are caching names

**Comment by tonihele** [comment]
We currently do this quite efficiently, though a bit manually but nevertheless it works. We try to find the file regardless it case. Closing.
