### ISSUE TITLE
Implement creature control

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#16]
Implement creature control. I believe that this is how these things work. We should be able to call these walk, run, hit1, hit2 etc and the control, well, controls the creature. The data is in Creature data registry. The control could acquire this data from the creature it is attached to.

**Comment by meltzow** [comment]
hi, is there any concept for selecting units?

**Comment by tonihele** [comment]
Hi,
nothing exists yet. In the original game I believe only these actions can be administered by the keeper, not really a selection, but closest to that:
 - onHover: makes the "flower" billboard visible for awhile (exp, level & health)
 - If pickable, can pickup (stack, last in, last out?), they are dangling then on the keeper's hand
 - If slapable, slap!
^ these are both PlayerActions and CreatureControl actions?

For the creature animations, currently an array of ArtResources, has been separated and identified by good sir Grégory Boré. I'll implement them shortly. I have no experience on making these functional controls, so I have very little idea at the moment how to tie all these together.

**Comment by meltzow** [comment]
ok, in JME there is the "Custom Controls Pattern" ( see here http://wiki.jmonkeyengine.org/doku.php/jme3:advanced:custom_controls ). Sounds like we need some CustomControls.

**Comment by meltzow** [comment]
and I found this nice thing: http://wiki.jmonkeyengine.org/doku.php/jme3:advanced:steer_behaviours

**Comment by tonihele** [comment]
Yes, controls. I have the 2 books of JME. They have quite complete examples on how to make controls & how to tie them to an AI. Hopefully helpful. Steering Behaviors I think nowadays only exist withing the MonkeyBrains. Latter being a bit problematic, there are no JAR's etc. The code needs to be forked if used.

My only major concern is how to patch a creature together really. By my simplest scenarios we just when loading, create ready instances by the level data. And clone them from there. And these instances are just made out of these multiple models that we load according to the data. However our models are quite big, especially the animated ones. And I don't really know if this is ideal. As then we would play with culling etc. to hide the nodes and only show the one with the current animation we want. Is this heavy or not?

I think the ideal structure would be:
 - Node(Imp)
  - AnimControl(walk1)
  - AnimControl(walk2)
  - ...

We would have currently:
 - Node(Imp)
  - ImpWalk
    - AnimControl(anim) 
  - ImpWalk1
    - AnimControl(anim)

Multiple pose frames. Maybe it doesn't matter, at least at this point. Overthinking perhaps....

**Comment by tonihele** [comment]
Oh and I yesterday commited much of ArcDemon's code, there was some kind of handling for which way the creature should face (while moving etc.). I don't know if it is working or not, or did I understood it correctly.

**Comment by meltzow** [comment]
how we can find out, which kind of GameCreature (for example a imp) we have?

**Comment by tonihele** [comment]
It has the id, on the info field. KwdFile instance can be used to get the creature data record.

**Comment by meltzow** [comment]
and where is mapping? which id is for the imps?

**Comment by tonihele** [comment]
ID 1 for the imps. Hopefully you won't really need to know that :) Meaning that it should be very generic. Imps just have IS_WORKER flag. If you convert a dwarf, it is a worker as well and should work as such.

**Comment by tonihele** [comment]
This goes hand-in-hand with the AI so this will be done at the same time (the initial version). I'll take it.

**Comment by tonihele** [comment]
Initial version done
