### ISSUE TITLE
Implement mana economy for all players

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#170]
Implement mana economy for all players. If I may suggest, similarly than I currently did the gold economy. ManaAppState that goes through all tiles & creatures, and calculates for all players. AppState is convenient since it would be easy to run in ticks (once we implement #147).

There is currently one implemented by @ArchDemons. As was the gold thingie I mentioned. And the basis is good, just need to expand and unify with the gold (and now it traverses the scene graph instead the stored objects). The gold is more event based, and for the mana I think it is just easiest to loop everything.

**Comment by tonihele** [comment]
The gold economy implementation is still in #148 feature branch. As are the object lists, so blocked until the branch is merged.

**Comment by ufdada** [comment]
What tasks are still open here?

**Comment by tonihele** [comment]
The whole task. Like PlayerGoldControl. It is just a record to easily get the player's economy. However PlayerManaControl is "too smart". It actually does the calculating. Executed per frame. I would like this calculating logic be on its own state, it could on the same loop calculate all players. And in separate thread, our new GameLogic thread. And from the "data", not the scene graph.

A small adjustment. We just previously didn't have creatures as catalog and what not. Mainly just refactoring this task.

I am not sure how the multiplayer should work. So that is why TaskManager for instance has player IDs for whom it scans the tasks for. But for simplicity's sake this kind of behavior can be left out, just calculate for all.

**Comment by tonihele** [comment]
Looping the map and keeping separate record would be just too complicated and unnecessary. Two loops? One for the map tiles and one for the creatures. Room ownership is on my local computer still (Dungeon Heart...) but it can be added later. And rooms could have a getter how much they contribute to mana flow (as extra).

**Comment by tonihele** [comment]
I guess this one is done in this scope already.
