### ISSUE TITLE
Figure out the Variables data

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#18]
Figure out the Variables data. Most of it is just trivial (but huge & dull effort). But the GlobalVariables at least is something else and it requires special handling. And knowledge to be gathered from yet unknown sources.

**Comment by tonihele** [comment]
ArchDemon's did this quite a bit. I merged his findings and I'll try to dig some more. I accidentally broke this by putting the file paths to hash by the ID. And there are 2 with variable ID. But the variables seem to come out nicely perhaps and always in order. So that GlobalVariables.kwd first and then the level ones. Just need to hash the different variable types to their own hash lists and the overriding will play itself out automatically.

**Comment by ufdada** [comment]
for reference: Archdemon added some more with #111

**Comment by tonihele** [comment]
Closing this, there are few unknowns like in all our data, but @ArchDemons did amazing job with this and it is certainly usable.
