### ISSUE TITLE
Fix Temple construction

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#185]
Fix Temple construction. Ours look quite not right. There might be even model level changes required (some weird transparencies)...

**Comment by codenamecpp** [comment]
What's wrong exactly with currently implemented temple? Could you post screenshot for comparsion?

**Comment by ufdada** [comment]
Here you are:
![temple](https://cloud.githubusercontent.com/assets/3787188/17275836/74f9f208-5716-11e6-9008-d036e1583692.png)

The arches shouldn't be transparent, also the holy water is also missing.

**Comment by codenamecpp** [comment]
Maybe dungeon geometry should be drawn without AlphaBlending?
I guess water mesh might be generated simple.

**Comment by tonihele** [comment]
The water could just use the same construction than the normal water. The
transparency might be caused by the asset generation. I used the file names
to guide some stuff. There are still unknown flag values. So I dont know
what is right.

On 31 Jul 2016 13:47, "Владислав" <notifications@github.com> wrote:

Maybe dungeon geometry should be drawn without AlphaBlending?
I guess water mesh might be generated simple.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tonihele/OpenKeeper/issues/185#issuecomment-236423241>,
or mute the thread

**Comment by belgianguy** [comment]
Files containing the arches:

- TEMPLE10.kmf
- TEMPLE12.kmf

**Comment by belgianguy** [comment]
The error seems to originate from: toniarts/openkeeper/tools/convert/textures/enginetextures/EngineTexturesFile.java:91
The unsigned integer here always has a value of 117 and 245.

`entry.setAlphaFlag(ConversionUtils.readUnsignedInteger(rawTextures) >> 7 != 0);`

The check here will evaluate whether to set the value of the AlphaFlag gets set to true or false.
For EngineTextureEntry with name "Slab FloorMM0" this evaluates to true and thus the alpha blending becomes active (and finally shows up in the arches of the temple).

If I change that boolean flag to false by hand while debugging, the temple arches render correctly.

The question is thus, do we need to look at more or other properties to define when an EngineTextureEntry should have its AlphaFlag set to true?

**Comment by ufdada** [comment]
Setting the alpha this way seems really weird.

For me it looks more like the transparency was set via it's name.
Example:
```
#TRANS50#D FairyMM0 // Transparency 50%
#TRANS25#iceyMM1 // Transparency 25%
```

**Comment by belgianguy** [comment]
So checking for substring #TRANS seems a better solution then?

**Comment by belgianguy** [comment]
And they number following the string perhaps points to a percentage?

**Comment by belgianguy** [comment]
And then in code you'd call setFloat("m_AphaValue", 0.5f); to get 50% alpha.

Source:  https://hub.jmonkeyengine.org/t/setting-the-opacity-of-an-already-partially-transparent-texture/14905

**Comment by belgianguy** [comment]
I've tried it, but at least for the fairy still pose, the textures used are:
- fairyfrnt
- fairyBack
- &mask&wing1

So we need to find out if there are extra flags available.

**Comment by belgianguy** [comment]
[material_flags.txt](https://github.com/tonihele/OpenKeeper/files/913980/material_flags.txt)

I've used a small script to list all flags a KMF can contain, maybe we can deduct the functionality by comparing and experimenting. I specifically looked into what could possibly trigger the alpha values, when it was not set in the name of the texture (using #TRANS). This might perhaps also be useful in #52 

My current guess is the following:
- UNKNOWN1 == HAS_ALPHA
- UNKNOWN2 == IS_REFLECTIVE (a highlight of some sort)

UNKNOWN1 and UNKNOWN2 flags are both part of the fairy model, but when looking at "Gold Chest.kmf" we can see that it only uses UNKNOWN1.

UNKNOWN2 is used for the Goblin, specifically the tip of his sword, maybe we can see something ingame in DKII what is being done there? Also the beak and feet of the chickens use UNKNOWN2.

Can somebody maybe verify this guess?

**Comment by belgianguy** [comment]
![hackbit](https://cloud.githubusercontent.com/assets/3091512/24931836/1678c6f2-1f0f-11e7-88b0-1cf9225c63e9.png)

**Comment by belgianguy** [comment]
As seen in the above picture, a fairy normally has flag 3 set for its materials. This breaks down to binary flags 1 and 2 (1 + 2 = 3). I determined that flag 1 is used for the alpha blending of the wings, but could not yet tell what happened when I set the flag to value 2. So that's still an open question, the fairy moves around quite a lot so I had to chase them across the map. :)

Flag set to 0 for testing: 
![flag0](https://cloud.githubusercontent.com/assets/3091512/24933561/380d753a-1f17-11e7-91ad-75d21947213a.png)

Flag set to 1:
![flag1](https://cloud.githubusercontent.com/assets/3091512/24933559/380a7240-1f17-11e7-99e9-b9875db07422.png)

Flag set to 2:
![flag2](https://cloud.githubusercontent.com/assets/3091512/24933562/382c5f22-1f17-11e7-9515-2e05bafed294.png)

**Comment by tonihele** [comment]
Nice work! UNKNOWN1 == HAS_ALPHA looks definitely correct looking at your evidence. So we could use that alone then, no need to dig up the EngineTextureEntry. Perhaps the file names could also be forgotten.

**Comment by tonihele** [comment]
I think it works, I tried to set the transparency only according to UNKNOWN1 flag. And Temple & Fairy worked. And the game. Didn't check all the models.

**Comment by tonihele** [comment]
UNKNOWN3 == Alpha Additive :) Then the main menu beams will work also.

**Comment by tonihele** [comment]
Here, you can take this out for a spin. Before you do, delete all from \Converted\Materials\. It'll break the ModelViewer, but that is a simple fix. I just, my environment is a WIP, so...
[issue185.zip](https://github.com/tonihele/OpenKeeper/files/917504/issue185.zip)

**Comment by tonihele** [comment]
We can take the EngineTexture stuff completely away from the KMFLoader, just rely on the flags.

**Comment by tonihele** [comment]
Forgot this, this is the material:
[issue185_2.zip](https://github.com/tonihele/OpenKeeper/files/917549/issue185_2.zip)

**Comment by ufdada** [comment]
Great findings guys :).

Just as reference #52

**Comment by tonihele** [comment]
Maybe UNKNOWN8 is some sort of glow. Like a small bloom effect. UNKNOWN2 shininess. But these require some sort of color?

**Comment by tonihele** [comment]
Damnit, I had one job... I tried to rebase. Put instead made a bit mess... Anyway we agreed with @belgianguy that I push the model stuff in. It is now in the master. You need to delete the Converted/Materials folder. Before running.

So what is needed is just the water, should be easy. Hopefully. And further material discussion should be put the issue #52

**Comment by belgianguy** [comment]
I did manage to come up with a function to check where the water tiles are supposed to be, ideally these will be in a List, so we can just test against it when iterating through the temple Points in constructFloor.

Got a bit stuck here, as in Temple.java: constructFloor function there is no access to mapData, (unless you explicitly add it, which probably is not the way to go), the WaterConstructor expects many arguments (like KwdFile, which also can be gotten from MapData, but which is probably also "bad practice").

Am I looking in the wrong place? Is there any info on "how to add water to a tile", as this needs to be recalculated every time the player builds/sells a piece of his Temple.

**Comment by ArchDemons** [comment]
@belgianguy, why you need mapData or kwdFile? Temple water exist on tiles with all neighbours. You can take this information from roomInstance.getCoordinatesAsMatrix() or roomInstance.getCoordinates(). Water construction you can find in file toniarts.openkeeper.world.terrain.Water

**Comment by tonihele** [comment]
I did some experiments. And really our double quad implementation is not that far off. It just looks that we don't follow the all neighbor -rule (incl. diagonal). That is why our prisons and temples fail on some irregular shapes. For temple the rule also means water but for everyone it means that this is an inside tile.

**Comment by tonihele** [comment]
Not really based on @belgianguy 's solution. And might not be as elegant. At least no unit tests which of course would have been nice. Now it is just same if else stuff that we have elsewhere also. Might not be that readable but I was unable to create some fancy algorithm. Still should not be too slow, I tried always to use the matrix to lookup stuff instead the roomInstance. The latter does use binary search but still it is a lot faster to just get them from the matrix.

This fixes all the double quads such as Prisons and Combat pits also. They didn't render correctly and sometimes even the door was missing rendering them unusable.

Temple places candle sticks instead of pillars. The logic is the same as in Workshop and it was copy pasted from there. Hand placement and door placements all should be now as in the original.

One minor issue remains. Again with the transparencies. When you have this outer corner on top of the water, the corner overlaps the water. But yeah, very minor, we can look it up another time.

**Comment by tonihele** [comment]
Also this issue remains https://cloud.githubusercontent.com/assets/3787188/25574090/3de96340-2e4b-11e7-9978-5b28d641db0c.jpg. It required knowledge of other rooms inside a room, we don't have that. Minor issue,

**Comment by tonihele** [comment]
Test map:
[doublequadtest.zip](https://github.com/tonihele/OpenKeeper/files/3220327/doublequadtest.zip)
