### ISSUE TITLE
Figure out the Triggers

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#19]
Figure out the Triggers. It is mainly done at this point. But there are couple of unknowns and the mapping of these triggers to the various items is not done. All this should be done in that way that it is easy to actually make them work in the game eventually.

**Comment by tonihele** [comment]
The triggers are stored as a kind of linked list. Knowing their child and/or the next sibling. But I have no idea how the triggers are attached to the main items i.e. how a trigger is a child of an ActionPoint. This data seems not to be with the trigger itself at least.

**Comment by tonihele** [comment]
I think we have this, the scope this issue is referring to. I'll check later... I think @ufdada filled in some.

**Comment by ArchDemons** [comment]
I did a great job with the trigger. I hope you will enjoy. After holidays I`ll PR

**Comment by tonihele** [comment]
Sounds good!

**Comment by tonihele** [comment]
This is very far now thanks to @ArchDemons. Only that all the trigger features are not supported in our current state.

**Comment by tonihele** [comment]
This is so far, that only individual triggers / features needed by some triggers are missing. New issues for those. Good job!
