### ISSUE TITLE
Implement support for "other" MPD levels

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#203]
Implement support for "other" MPD levels. We already have the menu for selecting the fixed MPD levels. But there is a hidden, well, not very well hidden, but it seems that they planned to have 7 MPD levels. This 7th is accessible through the Other menu selection. We haven't implemented it yet.

MainMenuState similarly scans for the skirmish & MP maps, just scan for the MPD levels (the 6 wont be marked as such). So additional Nifty screen with table etc.

**Comment by ufdada** [comment]
I take this one!

**Comment by ufdada** [comment]
It's really weird, the textTableId of mpd7 actually points to 37 (MPD4) but it doesn't have any effect at all (i changed it and tried it in dk2 and it still showed the correct briefing).

Maybe they just hard coded it? Because i can't find any reference to the residx-file that would link to the correct Briefing file.

**Comment by ufdada** [comment]
Okay i digged a little bit deeper in it, quite interesting.

The Name actually seems completely static. For example i created several mpd maps, all where named as mpd7. The briefing is actually hard coded for the first entry. The other ones really care about the textTableId.

Some custom maps use the campaign text files and write their stuff in the placefiller. We should definitely support custom text files (e.g. text files having the same file name than the map if the texttableid is none.)

**Comment by tonihele** [comment]
> Some custom maps use the campaign text files and write their stuff in the placefiller. We should definitely support custom text files (e.g. text files having the same file name than the map if the texttableid is none.)

That kind of custom support would be a great idea.
