### ISSUE TITLE
Fix cursors to support other formats than RGBA 32-bit

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#217]
Fix cursors to support other formats than RGBA 32-bit. I tried to load SpellPossessNoGo.png and it failed.

We currently use JME's image and a low level buffer. Maybe we could just construct the cursor from BufferedImage. It gives some abstraction over the underlying format. And if alpha channel is not present, use the top left pixel as the transparent color.

LWJGL 3 or the JME bridge has some changes. The cursor comes out flipped and with blue tint. We're not jumping on LWJGL 3 yet, but if we have some insights on this, it would be nice to share them here :)

**Comment by ufdada** [comment]
@ArchDemons has some code bits in here: https://github.com/tonihele/OpenKeeper/compare/master...ArchDemons:feature-220
