### ISSUE TITLE
Implement system messages

### ISSUE THREAD

**Issue by ufdada** [tonihele/OpenKeeper#220]
System messages are used to lead the player throughout the game.

Some features:
- most of them are actually voiced over by the mentor
- they fade in from right to left
- they have a lifetime (about 50 seconds) and then disappear
- they blink if they are unread (info messages in blue, important ones in red), otherwise (hover and read) they just show the white icon
- right click dismisses them (they are removed without animation)
- some have a magnifying glass to move the camera to a specific place, attach it to an object.
- ✘ dismisses them, ✔ just keeps them
- on hover, their text is shown in the tooltip label.
- Huge texts have scrolling

I wasn't able to find out what happens if you get to many of them, like if the first one get deleted or some kind of scrolling is happening

**Comment by tonihele** [comment]
Excellent. Maybe a test level can be made that has huge amount of triggers
creating messages and see what the original does. And also to test our
implementation.

**Comment by ufdada** [comment]
I am currently on it, small update:
![main1](https://cloud.githubusercontent.com/assets/3787188/17907215/221be18c-697b-11e6-97e2-3fa109885151.png)
The scrollbar stays even if there is nothing to scroll, but i don't think this is really a blocker.

**Comment by tonihele** [comment]
Nice :) Not a blocker :) There are other issues as well, one it the cursor. Also a minor issue.

**Comment by tonihele** [comment]
BTW, are you also creating the actual mechanics as in a message pool etc. Or just the UI stuff?

**Comment by ufdada** [comment]
i also wanted to do at least a basic implementation

**Comment by tonihele** [comment]
Oh, be my guest, I didn't do any code yet, just iterated in my head. But it should be really simple anyway. Only slightly complicated choices are whether to incorporate the funny/timed messages there or create a messaging singleton & MentorMessageState for the funny/timed stuff etc.

One thing I ruled out was LibGDX messaging system, it is good for other purposes. I don't think it suits this one perhaps.

**Comment by ufdada** [comment]
I didn't do much code yet, so even a restart shouldn't be problematic.

Currently i was prototyping a crude State with a linked list and a simple message class, which holds it's properties (unread, message text, etc.). But I am thinking about using a custom nifty controller for every message instance, so i don't have to care too much about the message list.

**Comment by tonihele** [comment]
Sounds good

**Comment by belgianguy** [comment]
Isn't there also a yellow one with a creature symbol when a new type of creature enters the dungeon?

**Comment by ufdada** [comment]
Yes, there are a few types actually. Like ally, allymsg, playerexit, creature, fight and info. I try to keep it as generic as possible, so it should be easy to trigger it and to display information (like the creature information when you are using the question mark tool)

**Comment by ArchDemons** [comment]
I almost wrote some code. I'll post it tomorrow. I have a problem with images in the icon of message. Image does not want to load through the code

**Comment by ufdada** [comment]
Sounds good, i would figure out why

**Comment by ArchDemons** [comment]
https://github.com/tonihele/OpenKeeper/compare/master...ArchDemons:feature-220

**Comment by ufdada** [comment]
Wow thanks, you've made quite a progress with the system.

**Comment by tonihele** [comment]
And with some other systems as well :)

**Comment by ArchDemons** [comment]
If I change the type of message is no icon in the xml file (e.g. ALLY):

> авг 25, 2016 7:38:28 PM toniarts.openkeeper.game.logic.GameLogicThread run
> SEVERE: Error in game logic tick on class toniarts.openkeeper.game.state.GameState!
> java.lang.RuntimeException: No OpenGL context found in the current thread.
> 	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
> 	at org.lwjgl.opengl.GL11.glBindTexture(GL11.java:651)
> 	at com.jme3.renderer.lwjgl.LwjglGL.glBindTexture(LwjglGL.java:50)
> 	at com.jme3.renderer.opengl.GLRenderer.bindTextureOnly(GLRenderer.java:2089)
> 	at com.jme3.renderer.opengl.GLRenderer.setupTextureParams(GLRenderer.java:1995)
> 	at com.jme3.renderer.opengl.GLRenderer.setTexture(GLRenderer.java:2256)
> 	at com.jme3.renderer.opengl.GLRenderer.modifyTexture(GLRenderer.java:2260)
> 	at com.jme3.niftygui.JmeBatchRenderBackend.modifyTexture(JmeBatchRenderBackend.java:361)
> 	at com.jme3.niftygui.JmeBatchRenderBackend.access$300(JmeBatchRenderBackend.java:75)
> 	at com.jme3.niftygui.JmeBatchRenderBackend$ImageImpl.modifyTexture(JmeBatchRenderBackend.java:392)
> 	at com.jme3.niftygui.JmeBatchRenderBackend.addImageToAtlas(JmeBatchRenderBackend.java:228)
> 	at de.lessvoid.nifty.render.batch.BatchRenderImage.uploadImageToAtlas(BatchRenderImage.java:197)
> 	at de.lessvoid.nifty.render.batch.BatchRenderImage.upload(BatchRenderImage.java:142)
> 	at de.lessvoid.nifty.render.NiftyImageManagerExtBatch$ReferencedCountedImageBatch.upload(NiftyImageManagerExtBatch.java:169)
> 	at de.lessvoid.nifty.render.NiftyImageManagerExtBatch.registerImage(NiftyImageManagerExtBatch.java:42)
> 	at de.lessvoid.nifty.render.NiftyImageManager.registerImage(NiftyImageManager.java:43)
> 	at de.lessvoid.nifty.render.NiftyRenderEngineImpl.createImage(NiftyRenderEngineImpl.java:182)
> 	at de.lessvoid.nifty.loaderv2.types.apply.ApplyRendererImage.apply(ApplyRendererImage.java:49)
> 	at de.lessvoid.nifty.elements.Element.initializeFromAttributes(Element.java:376)
> 	at de.lessvoid.nifty.loaderv2.types.ElementType.applyAttributes(ElementType.java:257)
> 	at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:198)
> 	at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
> 	at de.lessvoid.nifty.Nifty.createElementFromTypeInternal(Nifty.java:1816)
> 	at de.lessvoid.nifty.Nifty.createElementFromType(Nifty.java:1804)
> 	at de.lessvoid.nifty.builder.ElementBuilder.build(ElementBuilder.java:494)
> 	**at toniarts.openkeeper.game.MessagesManager.addMessage(MessagesManager.java:93)
> 	at toniarts.openkeeper.game.MessagesManager.addMessage(MessagesManager.java:98)
> 	at toniarts.openkeeper.game.MessagesManager.addMessage(MessagesManager.java:102)**
> 	at toniarts.openkeeper.game.state.PlayerState.setText(PlayerState.java:350)
> 	at toniarts.openkeeper.game.trigger.TriggerControl.doAction(TriggerControl.java:348)
> 	at toniarts.openkeeper.game.trigger.TriggerControl.updateControl(TriggerControl.java:106)
> 	at toniarts.openkeeper.game.control.Control.update(Control.java:68)
> 	at toniarts.openkeeper.game.data.Keeper.update(Keeper.java:131)
> 	at toniarts.openkeeper.game.state.GameState.processTick(GameState.java:335)
> 	at toniarts.openkeeper.game.logic.GameLogicThread.run(GameLogicThread.java:49)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by tonihele** [comment]
It happens because the game update loop can't update graphics at all. Even if we wouldn't have the multi-threaded approach on game ticks, it would come with multiplayer anyway. You need to enqueue the changes to the next graphics update cycle. I'm not sure how to always do this cleanly. Some parts of the system should not need to know this. Only the view controller parts.

**Comment by ufdada** [comment]
My approach is working fine in so far, i am just struggling with the message buttons.
![main2](https://cloud.githubusercontent.com/assets/3787188/17979798/b92a8e2a-6afc-11e6-893c-d8d6f2e36c61.png)
Just added a few demo messages to find errors.

**Comment by tonihele** [comment]
Looks gorgeus!

**Comment by ufdada** [comment]
I just noticed that the states aren't detached if a user decides to go back to the main menu. Is that intended? It's kinda awkward if the mentor sound is still playing while already back in the main menu.

**Comment by tonihele** [comment]
Yes and no. MainMenuState is persistent and so is PlayerState. Latter shouldn't be persistent, but it is because https://github.com/tonihele/OpenKeeper/issues/81 is not done. It would be logical to give the player ID to it in constructor. The UI XML takes some time to load. It is really the reason why PlayerState is existing. A bit premature optimization, but also a check that they load ok. And I think both do get detached but the instance is kept in memory?

Either way, everything else should be destroyed. GameState should be detached always when exiting to main menu. It detaches all the related states (and the related states should detach their related states and so on). Essentially all progress in the game is lost.

**Comment by ufdada** [comment]
Ah okay. i would keep it that way for that task (that means if you change your map the previous messages from another map are still there). Is that okay for you?

**Comment by tonihele** [comment]
Yeah, I think in the original game the message system was a "persistent singleton" also. MainMenu map has a trigger that simply turns the messaging off, I guess this means that silently prevents adding any messages to the message queue.

It would make sense that i.e. PlayerState would just flush the message buffer upon detaching. The menu would logically do the same, but in reality no need.
