### ISSUE TITLE
Figure out how to properly detect when the mouse is on the UI

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#226]
Figure out how to properly detect when the mouse is on the UI. Currently the PlayerInteractionState does this in isCursorOnGUI() by just figuring out the constraints of the main UI. There has got to be a better and more dynamic way to poll this from Nifty or let Nifty prevent the input etc. And it has to be lightweight solution.

The problem is clearly visible on the messages.

**Comment by ArchDemons** [comment]
https://github.com/tonihele/OpenKeeper/compare/master...ArchDemons:feature-226  something like that :-)

mouse position from left bottom corner, element position from left top corner... WTF ???

**Comment by ufdada** [comment]
Does that also cover the new message box? AFAIK the message box is inside the middle panel

**Comment by ArchDemons** [comment]
everything works as it should

**Comment by ufdada** [comment]
Okay :). Does the mouse action still propagate through the gui elements (like tagging a tile through clicking on a nifty element) ?

**Comment by ArchDemons** [comment]
rooms builds and sells. Tile tagging, tabs selects. Message window buttons clicks

**Comment by ufdada** [comment]
Wow i tested it myself and i am quite impressed. Incredible job ArchDemons :+1:
