### ISSUE TITLE
Implement creature flowers as materials

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#227]
Implement creature flowers as materials. Currently we are parsing it together with BufferedImage on the CPU (most likely on CPU....). #218 is perhaps the least concern, but GPU probably does this better anyway. Everything could be drawn there, just pass the textures and the percentage of level gaining, Could be a simple tutorial task on making materials :)

**Comment by tonihele** [comment]
The health could be a single texture we parse together and could change it by an index? Similar to our water.

There is also the neutral capturable creatures whose flower color animates with all player colors. If we could give an array of colors & change interval too?

**Comment by ufdada** [comment]
And there are objective marks too (Objective.png and Objective-2.png)

**Comment by tonihele** [comment]
Yes, that was not currently implemented (though if I remember correctly I reserved some space on the texture for it).

**Comment by belgianguy** [comment]
I do remember that sometimes there were enemies that had a circle with a lock at the bottom around their level flower, but I never understood what it meant.

**Comment by ufdada** [comment]
This means they were imprisioned

**Comment by tonihele** [comment]
Example how the research material went through is in https://github.com/tonihele/OpenKeeper/pull/376.

This is a bit more complicated but the most complex component might be the experience progress indicator which is solved in the said PR.
