### ISSUE TITLE
We should figure out a name for the game

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#23]
We should figure out a name for the game. OpenDungeonKeeper is definitely a cool name for a Dungeon Keeper remake. But it is also a name that will provide us with endless fountain of cease & desist letters...

OpenDK, another cool one, but OpenJDK is registered, too close?

OpenKeeper would be nice? In a logo the n -letter could be shaped a little like D.

Anyway, there is no hurry but we should refrain the use of the name OpenDungeonKeeper in the game itself (GUI, releases...).

**Comment by ufdada** [comment]
Well has it need to be something with "Open"? As this will be at least an enhanced version of Dungeon Keeper 2 what about DK2++? Simple, short and therefore easy to search/find. I think we should add the number of the game too, so it´s clear that´s a reimplementation of the successor.

**Comment by ufdada** [comment]
Luckily i had some time today to play a little with illustrator :).

See the DK++ icons:
https://github.com/ufdada/OpenDungeonKeeper/tree/icons/src/toniarts/opendungeonkeeper/gui/icons

**Comment by tonihele** [comment]
I like the icons. Simple & elegant!

The name is hard to come by, when we choose one, we stick to it forever. I agree that we should have the number 2 there somewhere.

**Comment by ufdada** [comment]
> The name is hard to come by, when we choose one, we stick to it forever. I agree that we should have the number 2 there somewhere.

I totally agree with this.
It was just a rough draft how the icon *could* look like! Shouldn´t be a problem to modify this icon to fit another name. The current one looks way too fussy in my opinion.

![opendk_256](https://cloud.githubusercontent.com/assets/3787188/5977145/616be48e-a895-11e4-8aec-712268147ed2.png)

**Comment by tonihele** [comment]
OpenDK seems to be in use already. And Google converts it to OpenJDK :)

OpenKeeper? OpenKeeper just brings out a 4 year old project in GitHub.

List of clones/remakes:
http://osgameclones.com/

Seems that the community is not a big fan of numbers.

With the curved style you are using, letter N already looks a little like D :)

**Comment by tonihele** [comment]
OpenKeeper it is. So we are finally legal and I can also type in the law stuff (GLP...) and we are a legit professional project :)

**Comment by tonihele** [comment]
Also the name change requires re-conversion of the assets. The animations had the old package name and they refuse to open.

**Comment by ufdada** [comment]
We should probably implement some versioning for the convertion process, so we can easily reconvert them if neccessary

**Comment by tonihele** [comment]
https://github.com/tonihele/OpenKeeper/blob/master/src/toniarts/openkeeper/Main.java#L71 ;)

So early stage of development that I am just too lazy to use it. But it works and it it already implemented :)

**Comment by ufdada** [comment]
Well it would trigger to convert all assets, isn't it? I was thinking more about versioning different parts (like textures 1.2, sounds 1.1, path 1.3) so it doesn't need so much time to reconvert this.

**Comment by tonihele** [comment]
That is true. Sure the system should be expanded as you described. It would support the development and the end-user better. The version CONSTS should probably be in the AssetConverter class for logical maintaining.
