### ISSUE TITLE
Texture warning

### ISSUE THREAD

**Issue by ArchDemons** [tonihele/OpenKeeper#245]
When I started game, I received those messages ( and many same others).
```
сен 18, 2016 6:56:02 PM com.jme3.asset.DesktopAssetManager locateAsset
WARNING: Cannot locate resource: Textures/Hatchery1_n.png
сен 18, 2016 6:56:02 PM com.jme3.asset.DesktopAssetManager locateAsset
WARNING: Cannot locate resource: Textures/Hatchery1_s.png
```
Hatchery1.png file exist only. **_n** and **_s** - some flags, I think. 

Somebody know what we must do with it?

**Comment by tonihele** [comment]
_n for Normal map & _s for Specular. A bit hax. I originally thought that artists could use the JME IDE & commit the material files. But I made this small hack to support trying out alternative textures with all the goodies. Not very pretty. https://github.com/tonihele/OpenKeeper/wiki/Custom-graphics.

https://github.com/tonihele/OpenKeeper/blob/master/src/toniarts/openkeeper/utils/AssetUtils.java#L130

**Comment by ufdada** [comment]
This behaviour is actually intended. The asset pipeline is looking for normal and specular textures. 
https://github.com/tonihele/OpenKeeper/commit/cfc32aa7dc10f0232cd0c32498b48a14dbda14c3

If it is too expensive we should add a switch to turn it off or on.
