### ISSUE TITLE
License and code header

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#26]
License and code header. We should decide on code license and add the license information among other information on code headers. NetBeans template isn't very professional looking :)

**Comment by tonihele** [comment]
GPL?

**Comment by ufdada** [comment]
If we take GPL, then at least v3 (because older Versions relied more on the american legal system). I don't think the MIT is interesting for this, it would be very unlikely that companies would adapt this code.

**Comment by tonihele** [comment]
GLPv3 it is.

Now, to set the code header to appear automatically. This will probably be easier in NetBeans 8.0 (JME 3.1?). But now unfortunately you need to add the license template yourself.

Following this:
http://javaevangelist.blogspot.fi/2013/07/netbeans-74-tip-of-day-adding-custom.html

The file name needs to be:
license-gpl30-openkeeper.txt

You can find our template in https://github.com/tonihele/OpenKeeper/blob/master/license.txt.
