### ISSUE TITLE
Implement skirmish/multiplayer lobby

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#274]
Implement skirmish/multiplayer lobby. We currently have them as separate screens. They should be united and abstracted so that it works on both cases.

I have this currently under the works.... But I created the ticket for if there is any discussion and I can map the merge then to this ticket.

I actually don't know how the screen appears on a non-hosting client. So if you have links or screenshots. You can post them here.

**Comment by ArchDemons** [comment]
[like this](https://cloud.mail.ru/public/Fkba/cLqoxgb6K) or  [this](https://cloud.mail.ru/public/RojS/aZx5K46qK) ?

**Comment by tonihele** [comment]
Thanks! Exactly like ours :) I was afraid they see the game settings. One small thing is, how to do the map max player thingie.

Now the process is the following:
 - Player joins, he gets the next available keeper ID (as in original)
 - Player leaves, no keeper IDs are changed (as in original)
 - Player leaves but there are too many players for the map, sort the players so that the keeper IDs are in sequence, 1;3;4 -> 1;2;3
 - 4 players can join the server when in the lobby phase
 - when map changes, sort the players so that the keeper IDs are in sequence, 1;3;4 -> 1;2;3 (as in original, I think)
 - when map changes and there are too many players, drop the extra AI players
 - now, when the game is started, drop the extra players that don't fit to selected map, maybe show a warning to the host, or to the chat when more players joined up than the map supports, or such smaller map is selected

Does this sound reasonable?

**Comment by tonihele** [comment]
Oh and I have no idea how the client marks itself not ready again. Maybe clicking the check button once again? And with the host this just starts the game if everyone is ready.

**Comment by ArchDemons** [comment]
1. if lobby have no free slots (even if it is busy by AI), player not enter in lobby
2. if players enter lobby he placed on first non AI slot (AI moves forward)
3. Lobby creator can not change map (or random map) if it slots < players (include AI). This buggy in game because i place 4 players and one AI was kicked, but not all when I change map (random map takes 4 or 3 players maps only).
4. if game starts with AI only, it is converts to skirmish game.

About button ckicking.
1. First click on "OK" button marks ready
2. Second click on "OK" button marks not ready
3. When all player ready - game starts.

**Comment by tonihele** [comment]
Thanks. I might modify this a bit, not all of this sounds like a standard behavior nowadays in multiplayer games.

**Comment by tonihele** [comment]
I'll add these here for easier access:
![lobby](https://cloud.githubusercontent.com/assets/8344766/25069644/df73e964-228f-11e7-94a5-a74cf3bc7a5a.png)
![lobby2](https://cloud.githubusercontent.com/assets/8344766/25069645/df774f64-228f-11e7-9f6f-ea78083a0c06.png)

**Comment by tonihele** [comment]
The skirmish & mp lobby were unified. I went ahead and created a LocalLobby as well. I'm not sure if this is smart or necessary. But I was hoping that when you play the game alone, we don't need client & server. If this causes lots of additional code and is not doable like I imagined, I'll scrap the local lobby then.

Some known issues remain. Nothing existing should be broken. But to play skirmish map, you need to add ALL the players in supported by the map. Otherwise lot of NPEs will occur.
