### ISSUE TITLE
OpenGL Issue

### ISSUE THREAD

**Issue by hgdagon** [tonihele/OpenKeeper#301]
So, I'm having this weird problem. So, the laptop I'm currently on doesn't "officially" support Win10, so windows downloaded a generic Intel driver, which doesn't work with pretty much anything that I build with msys2. Usually, I just drop msys2's `opengl32.dll` (the one that I'm linking against) next to the executable.

I'm not quite sure how to do that with java, though.

The error I'm receiving is:

`Failed to create display LGJWL exception: Pixel format not accelerated`

My videochip supports OpenGL 3.1.

**Comment by tonihele** [comment]
Well, this is just guesswork but I would imagine that java finds all the files pointed out by the path variable. Other option is that when you build the thing (at least the dist build), there should be few DLLs appearing, if you toss it there, I assume it uses it. Also if it runs far enough, there should be the config file appearing (in you user folder) and you can play with the color depth etc. to see if it helps.

Generally I've heard these Intel chips might be problematic. I've been using Skylake era Intel in Linux to run OpenKeeper and it works like a charm.

If you are interested enough you could debug it. Or try get JME and test the test projects that do they run, or is it just us.

**Comment by RobertZenz** [comment]
> Well, this is just guesswork but I would imagine that java finds all the files pointed out by the path variable.

It should be the `java.library.path` argument handed to the JVM.

**Comment by tonihele** [comment]
Did you get this to work? We now changed the rendered to LWJGL 3 from 2. It might make some difference as well.

**Comment by tonihele** [comment]
Assumed fixed then
