### ISSUE TITLE
Cursor wrong bitshift in ABGR8

### ISSUE THREAD

**Issue by etherblood** [tonihele/OpenKeeper#318]
'>>' in the following line should be replaced with '>>>', otherwise alpha will be 255 if red is >= 128 due to sign extension.
https://github.com/tonihele/OpenKeeper/blob/34707fd2a4f36c120e6bebafa11bac8f43e6c1ea/src/toniarts/openkeeper/gui/Cursor.java#L117

**Comment by etherblood** [comment]
And thanks for this useful class :+1:

**Comment by tonihele** [comment]
Great! Thanks for reporting this. I guess I'll have to take your word for it. Can't see any difference in results. Neither is the bit fiddling my cup of tea.

**Comment by RobertZenz** [comment]
@tonihele `>>>` clears the sign bit when shifting, `>>` does not. So with `>>` you're not only "shifting the value", but you're also "shifting the sign bit with the value".
