### ISSUE TITLE
Fix license.txt file so that it's easier to read, and so that GitHub detects it

### ISSUE THREAD

**Issue by Thunderforge** [tonihele/OpenKeeper#346]
Right now, [the license file](https://github.com/tonihele/OpenKeeper/blob/1f056310e575707a0f6966dc736b49de5b436c7c/license.txt) has a bunch of metadata of some sort in it:

```
<#if licenseFirst??>
${licenseFirst}
</#if>
${licensePrefix}Copyright (C) 2014-${date?date?string("yyyy")} OpenKeeper
${licensePrefix?replace(" +$", "", "r")}
${licensePrefix}OpenKeeper is free software: you can redistribute it and/or modify
```

As such, it's difficult to read, and GitHub can't auto-detect that it's a GPL-3.0 license. 

<img width="374" alt="image" src="https://user-images.githubusercontent.com/6200170/66889773-42c18100-efa9-11e9-86c5-b430a998d5d3.png">

If we change it to be a standard GPL-3.0 license, it looks like this:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/6200170/66889753-36d5bf00-efa9-11e9-846e-bcbcbd53eb66.png">

**Comment by tonihele** [comment]
This "metadata" is for the IDEs. So they automatically fill in the dates and whatnot. So we would need to still satisfy both, Github and IDEs, in my opinion.

**Comment by billotronic** [comment]
So pardon my ignorance, but couldn't you just use a different file name for your IDE info and then use the LICENSE.MD filename and default content to make github happy?
