### ISSUE TITLE
Figure out the room, spell, trap, door availability

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#356]
Figure out the room, spell, trap, door availability. Now that we have everything researchable, it looks as we don't perfectly understand the what is available and what is researchable. The code looks kinda odd, spells seem to be a special case according to it. This would be the setupPlayers() in GameController.

The availability structure goes so that first there are entries without player ID. Followed by player specific availability. These should be perhaps processed separately. Somehow it seems that they have different values. Might even be that we should start with full list and start eliminating? Dunno, a bit weird if our parsing of the file format is correct.

After #341 there are faulty entries in the campaign maps. Should be tested with campaign maps and custom maps alike (during campaigns one doesn't ever research rooms, not maybe even traps...).

https://lubiki.keeperklan.com/dk2_docs/dk2_editor_manual.htm#manual_walkth02availresrch

**Comment by tonihele** [comment]
Note that this also goes for the player creatures. Currently also broken.

**Comment by ArchDemons** [comment]
```
public enum AvailabilityValue implements IValueEnum {

            EMPTY(1),
            DISABLE(2),
            ENABLE(3),
            EMPTY_ROOM(4);
```
should be

```
public enum AvailabilityValue implements IValueEnum {

            Unavailable(1),
            Researchable(2),
            Available(3),
            Unavailable_ROOM(4); // maybe game bug
```

**Comment by tonihele** [comment]
Nice thanks!
