### ISSUE TITLE
this is Frame synchronization game?

### ISSUE THREAD

**Issue by qq1053831109** [tonihele/OpenKeeper#358]
this is Frame synchronization game?

**Comment by tonihele** [comment]
Could you be more specific what you mean?

We have a server authoritative architecture. And client side should have prediction, but at the moment that is not implemented. In any case very simple approach. I'm not exactly a professor of this topic :)

Our multiplayer works fine at least on LAN now.

**Comment by qq1053831109** [comment]
sever just forward only user actions？no object state！

**Comment by tonihele** [comment]
Server runs the simulation and doesn't really care about anyone. Clients try to keep up, but it is up to them. Server processes user input yes, but at least currently is just validates the user input against its current state.
