### ISSUE TITLE
walls are too straight

### ISSUE THREAD

**Issue by Yihka** [tonihele/OpenKeeper#454]
In the original games, each wall looks a bit off, giving a certain vibe to the game.

See the screenshot

![janky-lines](https://github.com/tonihele/OpenKeeper/assets/7753711/756e18e6-2a97-428e-8fd2-84ffa901f6c6)

**Comment by PieterVdc** [comment]
duplicate from #108

**Comment by Yihka** [comment]
Well spotted, closing this one
