### ISSUE TITLE
Figure out the .444 files

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#53]
Figure out the .444 files. Splash screens & loading screens are stored as files with the extension .444. It may or may not be the same compression used by the textures. But at least the headers are funny and I don't understand them. Totally unknown to me.

These files are extracted by the OpenKeeper asset converter.

**Comment by ArchDemons** [comment]
A few more days and I decoded files *.444. To understand how to do this, you need to see function of  direct draw CreateSurface() (I will clarify what exactly).

**Comment by tonihele** [comment]
Sounds great! Also may be worth noticing that assets\Textures\TitleScreen\ has Titlescreen-Japanese.444 & Titlescreen-Japanese.png. Maybe the same.

**Comment by tonihele** [comment]
Guess what, I just heard that they are TGI files, the same as the movies, and we already got a decoder for that.... Just need to figure out how to add the two together :)

**Comment by ArchDemons** [comment]
I will not yet deal with the file. If you do not get to deal with the file, then I will continue

**Comment by tonihele** [comment]
Yes, I've just hours ago received a C++ code for it (our TQI decoder didn't cut it, it might be near but out of my reach). We also have now #OpenKeeper @ Freenode, IRC. When I get my bouncer up and running I'll change our readme and advertise it there. Tomorrow perhaps, but the channel is now there. This would ease up the communication.
