### ISSUE TITLE
New icons for the game

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#54]
New icons for the game. Our current icons are based on the old name. We need a fresh look.

**Comment by tonihele** [comment]
@ufdada you care to take this one? :)

**Comment by ufdada** [comment]
Yeah sure, do you have any special requirments?

I would go something like that: https://github.com/tonihele/OpenKeeper/issues/23#issuecomment-72209715

**Comment by tonihele** [comment]
Looks good to me ! I don't know should we use the DK II palette on that, I'll let you decide.

\Textures\Thumbnails\MapColours.png, if you need it, it seems to contain all ? the colors. Not just "map" colors.

**Comment by ufdada** [comment]
What do you think about these?
![openkeeper-new-256](https://cloud.githubusercontent.com/assets/3787188/8683908/bfa8639e-2a75-11e5-9447-a76ee5f96f9b.png)
http://www.filedropper.com/logonew

![openkeeper-red-256](https://cloud.githubusercontent.com/assets/3787188/8683937/f1565356-2a75-11e5-9d31-4d70e6963238.png)
http://www.filedropper.com/logored

Feedback is always welcome :)

**Comment by tonihele** [comment]
Although I prefer the silver/green personally, I must say that keeping to the game theme colors makes a lot of sense. So I'd go with red/orange, it has a sinister feel to it also :)

Would it make any sense to have 2 different icons, sizes smaller than 32 would just say "OK"? 32x32 is still readable I think with the "Open Keeper".

**Comment by ufdada** [comment]
Shouldn't be too difficult. I'll have a look when i get home.

**Comment by ufdada** [comment]
![openkeeper-red-16](https://cloud.githubusercontent.com/assets/3787188/8706725/a3e13052-2b31-11e5-8d0a-5d508ffb64ac.png)
![openkeeper-red-24](https://cloud.githubusercontent.com/assets/3787188/8706724/a3e0d7c4-2b31-11e5-9039-e36fdcfa817d.png)
http://www.filedropper.com/logored_1

**Comment by tonihele** [comment]
Nice work! I'd commit them right away but we have now 666 commits, and Horny would be sad if I just went ahead and broke that :)

**Comment by ufdada** [comment]
:+1: You did that on purpose, right? :wink:
