### ISSUE TITLE
Convert \Data\Settings\HiScores.dat and add it to main menu

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#56]
Convert \Data\Settings\HiScores.dat. Read it and convert to JME binary we can easily use in the future. And while at it, add it to the main menu for real.

The format doesn't seem very hard to crack.

**Comment by tonihele** [comment]
One entry seems to be 76 bytes long.
int score (4 bytes)
string utf16 name (64 bytes)
string utf16 level (8 bytes)

Perhaps?

**Comment by ArchDemons** [comment]
https://github.com/ArchDemons/Keeper/commit/7dcf02dd1c26157a1ab20af8f5a6ea1857d0f8ad

**Comment by tonihele** [comment]
I've merged your changes, here is our implementation that can be used in the game:
https://github.com/tonihele/OpenKeeper/commit/5ce045f602b508d9116e52d0a05ada20bfeec21f

I'm going to swamp soccer world championships tomorrow and directly to work again on Monday etc. So I'm not implementing it currently to the menu. It is up for grasps if somebody wants it.
