### ISSUE TITLE
Add the view movies to the main menu

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#57]
Add the view movies (extras) to the main menu. It would be nice if part of the logic would also be there (can't watch movies the player hasn't unlocked yet). Of course this logic is implemented just GUI wise here. Since there is no progression nor play yet.

**Comment by ufdada** [comment]
Do you know how the logic is built?
I would actually go this way:
- Build the movie list with everything unlocked in the xml (and an id with the level number)
- Check on onStartScreen if the current level is smaller than the list item count
- get every movie that is higher than the current level and set it to "unavailabe" (image and message onclick)

**Comment by tonihele** [comment]
The suggested implementation is fine by me.

If my memory serves me correctly, @ArchDemons has already kinda implemented progression. I've yet to merge it. But there is also a catch that at this point these kind of systems just hinder the debugging (it is nice to access all levels from the menu). So whatever the system is, it should just be stubbed. Or the subsystems using it.

Creating the progression system is tempting since it is fairly easy and again creates an impression that our game is actually ready :)

I would not consider the progression thingy to be in the scope of this issue. So I would just stub it. Your checker would just do something like for() {isCutsceneViewable(level index)} and return true at this point.

**Comment by tonihele** [comment]
I don't remember did the DK II play them full screen. But you might stumble to this faulty design choice I made. The MainMenuState should be proper example like AppState (JME tutorials). That is, it should be always created, but it should be disable-able. Now it is not. So the scene just stays behind your cinematic.

I can change this later.

**Comment by ufdada** [comment]
As far as i already tested playing movies out of the main menu it seemed fine. But the sound still playing after canceling seemed a little disturbing...

**Comment by tonihele** [comment]
The movie material might occupy the whole screen, since the actual magic was performed in the shader and not in sizing the quad in the GUI node.. Well anyway, good that it works.

The sound thing. It is JAVA sound. I'm sure it can be fixed, and it should. I'll create another issue for it.
