### ISSUE TITLE
Implement hero lair building

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#72]
Implement hero lair building. This seems to be hard coded of some sorts. It doesn't seem to have a room record. Just a terrain record.

It uses floor: hero_outpost_floorX models.

**Comment by tonihele** [comment]
You can find these at MPD levels.

**Comment by ufdada** [comment]
Do we read from map globals yet? Maybe it's baked in there. Could be that ROOM_HERO_GATE_BIRDLESS which sounds quite interesting.

**Comment by ArchDemons** [comment]
Before that, we need to refactor MapLoader. When we construct tiles, we must use only Flags, not resources. Once upon a time I began to work on this, but did not finish. Since then, much has changed...

P.S. Firstly need resolve #127

**Comment by tonihele** [comment]
Implemented in:
https://github.com/tonihele/OpenKeeper/pull/132
