### ISSUE TITLE
Implement user & app settings

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#77]
Implement user & app settings. In separate files. Since we already write to application "install" folder, which is nowadays a big no no (UAC on Windows, privileges), it doesn't matter much to also write the application data there. And the user data to user folder.

App settings:
DK II folder + conversion versioning

User settings:
Everything else

User settings should be categorized.

Implementation example for user settings:
public class UserSettings {
public enum Controls implements ISettingsEnum {
ZOOM_UP(Integer.class, Mouse.WHEEL_UP.getValue()),..
}
...
}

**Comment by ufdada** [comment]
This should go hand in hand with the level progress. Dungeon Keeper uses a very easy to understand mechanic in the windows registry to do that (but they weren't that consistent).

Usually the progress was stored as a string with a the first two bytes as progression and three bytes as delimiter.

**Level Attempts:** The number of times you tried to play the campaign level. probably never really used.

**Level Number:** The campaign level you are currently on (used for the "Continue" level selection screen)

**Player Level Status:** Sets the status of the campaign levels. 1 = completed, 2 = the level you are currently on, 3 = not completed (don't forget that some levels are divided in two or three different similar levels) (XX 00 00 00)

**Secret Level Number:** The secret level you are currently on

**Secret Levels:** Sets the bonus levels that you have discovered. 1 = discovered, 0 = not discovered (XX 00 00 00)

**Secret Levels Completed:** Sets which secret levels you have completed. 1 = completed, 0 = not completed. (XX 00 00 00)

**Pet Dungeon Levels Completed:** Sets the MPD levels that are completed (XX 00 00 00)

**MPD Level Number:** The MPD level you're currently on

Dungeon Keeper has quite a lot of hidden settings that we should keep in mind: http://www.deindungeonistvollerjoghurt.keepfree.de/dk2regkeys.txt

**Comment by tonihele** [comment]
Thanks, that is a  good base. I don't think we are going to migrate them (although it would make a little sense since we did the hiscores even :), but Windows and registry). The level progress, I don't see any reason to change it.

I think we should use the JAVA Preference API. It is usable also through JME AppSettings. It is the right way to do things. It just means that the settings will relocate.

**Comment by tonihele** [comment]
AppSettings in JME is final. This is a bit perversed, but I think it works. We can adjust it later when the need arises. Now however it should be simple to add those numerous control settings, get automatic translation for them etc. Can be used to dynamically built GUI with.

**Comment by tonihele** [comment]
Hmm, the key is a bit redundant. I'll get rid of it. The key can be generated from the enum literal...
