### ISSUE TITLE
Fix our camera rotation

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#80]
Fix our camera rotation. We now have our own camera controls. They are that of original DK IIs, except the arrow keys are switched by default to WASD. And mouse wheel also acts as a zoom. There are no restrictions to the camera movement as of yet, mainly this camera is because it makes things easier to implement. It acts as the original and the keys don't intervene with player actions.

Oh the camera rotation... DK II style it should be, probably simple to implement if you have any understanding of the 3D space. I don't.

**Comment by tonihele** [comment]
Maybe we need a camera node on the ground. And the rotation rotates the node (also moving would move the node, only "zooming" is moving the actual camera). That would make the camera circle the camera node. Probably.

**Comment by ArchDemons** [comment]
...
Vector3f dir = cam.getDirection();
        
Vector3f pos = cam.getLocation();        
Vector3f look = dir.mult(-pos.y / dir.y).add(pos); // Where lookAt camera
pos.subtractLocal(look);
       
mat.mult(up, up);
mat.mult(left, left);
mat.mult(dir, dir);
mat.mult(pos, pos);

Quaternion q = new Quaternion();
q.fromAxes(left, up, dir);
q.normalizeLocal();
        
cam.setLocation(look.addLocal(pos));
cam.setAxes(q);

**Comment by tonihele** [comment]
Great that someone understands math & 3D :)
