### ISSUE TITLE
Refactor ScreenControllers out of AppStates

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#81]
Refactor ScreenControllers out of AppStates. It has become quite clear that the way we do things isn't viable on the long run. The AppStates should handle the logic stuff, and serve the ScreenControllers to handle the GUI. Not both. MainMenuState has 1000 lines of code. That is nice, we are a bunch of hard working people, except it starts to be too complex & messy.

So what we need is kind of MVC model system, I use the term quite loosely here. But the AppState serves as model to the ScreenControllers. ScreenControllers just handle the GUI building. Not all screens need their own ScreenController if it doesn't have any logic, just transitions etc.

The XML files could also be possibly splitted, styles are in separate style file and bundles & other stuff I think are globally registered to the Nifty instance. So i.e. Interface\MainMenu\*.xml.

So MainMenu example:
 - \gui\nifty\mainmenu\MainMenuController.java (base class for the main menu screen controllers, holds instance to the MainMenuState & basic functions such as transitions, simple screens can use this)
 - Any complex screen should have it's own controller

Main.java would load things as usual. All XML and controllers like now, memory is our friend, and these don't take so much of it anyway. Cuts loading times.
 - After constructing the state, asks state.gimmeYourScreenControllers() and registers these to Nifty
 - Also asks for the XML files from the state so that it can load them, if they are separated too (no longer a huge XML)

**Comment by tonihele** [comment]
I didn't try this, but from what I've seen this should be possible and to me it sounds logical.

**Comment by ArchDemons** [comment]
https://github.com/tonihele/OpenKeeper/compare/master...ArchDemons:complex 

I need a little time to implement some of these changes. I do not want to break your branches. Rebase - is always hard work...

Tell me when you're ready

**Comment by tonihele** [comment]
There is nothing much going on. Just the room furnishing, but I can't give an ETA for it. I'll try to make it functional, not only visuals. Still a small branch, so go ahead if you have something ready, I'll try to adapt :)

**Comment by tonihele** [comment]
Or I can merge actually now, the branch doesn't break anything at this point. Just adds some stuff and I actually refactored the Thing.Room thing which was kinda haxed in. Is that a reasonable solution? :)

**Comment by ArchDemons** [comment]
Yes, it would be better

**Comment by tonihele** [comment]
Merged my branch
