### ISSUE TITLE
Basic world interaction

### ISSUE THREAD

**Issue by meltzow** [tonihele/OpenKeeper#82]
hi,
is there any concept/idea for Basic world interaction?
what should be the first? 
I think realizing Imps are a good start, isn't it? How can we do this?

**Comment by tonihele** [comment]
Hi,

I'm glad your interested getting your hands dirty :) I should create smaller issues to break this one down. Before the imps we need:
 - Tagging/detagging tiles (already in @ArchDemons' branch)
 - Terrain modifications (see #79)
  - (Selling buildings)
  - (Buying buildings)
  - Removing tiles
For the imps itself we need:
 - A concept for loading creature entities
  - Controls, animations etc
 - Basic AI + navigation

**Comment by tonihele** [comment]
@ufdada is in progress of merging some basic stuff from @ArchDemons' branch. There is also a creature loader if I remember correctly, but just a basic one.

**Comment by meltzow** [comment]
I close this general issue because there are smaller issues for all things.
