### ISSUE TITLE
Implement tagging terrain

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#86]
Implement tagging terrain. If it is taggable, we should be able to tag it. @ArchDemons' branch has many of these features already. We don't have AI and job queue at this point, so graphical tagging is sufficient.

So:
 - Tagging, de-tagging
 - re-batching...
 - Dragging with mouse + multitagging
  - As a super bonus, showing the area size selecting (like "5x5") <- not original DK II, but very good example in War for the Overworld

#79 might serve as blocking issue.

**Comment by tonihele** [comment]
The new scene graph performs nicely, 8x8 blocks, might even use bigger ones. My old i5 doesn't mind at all at least. I currently clear & re-create the contents to to tiles needed to be changed, and then batch. Works like a charm.

**Comment by ufdada** [comment]
The new scene graph improved the loading times a lot, good job :)

**Comment by tonihele** [comment]
Only thing that is a bit messy is my perversion to have the map files read only (no engine stuff), so currently I have some ugly wrappers around MapLoader and Tile to make them editable. I'll try to tidy it up a bit, that's why no commits. But after that, basic building, selling and other terrain modifications are a breeze.

**Comment by tonihele** [comment]
Very basic, and the interaction is now locked to selection + missing textures (should generate these, as there are only few of those ready with DK II, so better to add just a transparent layer to the existing versions).

I think the newly created PlayerInteractionState should get the player states and manage whether it is tagging or building etc.

**Comment by tonihele** [comment]
![tagging](https://cloud.githubusercontent.com/assets/8344766/10802245/7494993e-7dc4-11e5-8b58-1bbc212692ad.png)
Dig god dammit! :)

**Comment by ufdada** [comment]
:+1:

**Comment by meltzow** [comment]
great stuff.
