### ISSUE TITLE
Shortcut for starting Map

### ISSUE THREAD

**Issue by meltzow** [tonihele/OpenKeeper#92]
To realize a faster development it will be great if we have a possibility for starting a map directly without clicking though the menu.

**Comment by tonihele** [comment]
I use the level flag to make shortcuts in the IDE. If you use the level flag, you don't need the -nomovies. It skips them anyway and starts the level.
https://github.com/tonihele/OpenKeeper/wiki/CMD-line-parameters

**Comment by meltzow** [comment]
perfect. thy. thats what I need

**Comment by tonihele** [comment]
Oh and to get to the menu for whatever reason from the game, you can use the computer icon near the minimap placeholder. It opens the in game menu.
