### ISSUE TITLE
Implement creature slapping

### ISSUE THREAD

**Issue by tonihele** [tonihele/OpenKeeper#97]
Implement creature slapping. SLAP!

Can slap. Slapping should result in visual violence. The creature needs to know it has been slapped. No mood etc changes required. Nor blood decals. 

Probably waiting for #16 to be really usable.

**Comment by Birdasaur** [comment]
This is the single most important feature in the entire game. All our hopes rest on you.

**Comment by tonihele** [comment]
Initial version done

**Comment by ufdada** [comment]
really looking forward to it :+1:

**Comment by tonihele** [comment]
There is no direction yet and they kinda tend to just continue their business afterwards :) But getting there...

**Comment by ufdada** [comment]
As long as the sound is playing i would be happy at first glance :)

**Comment by tonihele** [comment]
Implemented the Keeper sound but no cursor (as it is not so simple yet, need to create timer for changing cursor). No direction nor decals nor creature sound (as I don't want to hard code this). Wrong animations. But you can actually kill your creature, whether that is a good thing then...
